name: schedule

# 任务触发
on:
  # 当 提交到当前仓库时立即运行
  push:
    branches: [ main ]
  schedule:
    # 东八区07:00，约莫有延时10~20，看github服务器情况
    - cron: '0 23 * * *'
  
  # 当star当前仓库时立即执行
  watch:
    types: [started]

jobs:
  # 自动打卡任务
  autocard:
    # 使用ubuntu作为运行的OS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      #上游同步
      - name: Sync with upstream
        if: github.repository != 'GCS-ZHN/AutoCard'
        continue-on-error: true
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.2
        with:
          upstream_sync_repo: GCS-ZHN/AutoCard
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_pull_args: '-s recursive -Xtheirs'

      # 安装java环境
      - name: "Setup Java"
        uses: actions/setup-java@v2
        with:
           distribution: 'temurin'
           java-version: '17'

      - name: "Setup maven"
        uses: stCarolas/setup-maven@v4.3
        with:
            maven-version: 3.8.2

      - name: "Setup tesseract-ocr"
        run: "sudo apt install tesseract-ocr -y"

      - name: "Cache maven dependencies"
        uses: actions/cache@v3
        with:
            key: autocard_${{  hashFiles('pom.xml') }}
            path: "~/.m2/repository"

      - name: "Compile source"
        run: "mvn clean package spring-boot:repackage"

      - name: "Configure file"
        run: "rm -rf config && mv action/config config && mv target/autocard*jar autocard.jar"
      
      # 缓存信息，当缓存发生变化时，请修改key值
      - name: "Cache autocard cache file"
        uses: actions/cache@v3
        with: 
          key: autocard_cache-${{ hashFiles('config/application.json') }}-${{ hashFiles('autocard.jar') }}-${{ secrets.AUTOCARD_CACHE_FLAG }}
          path: "autocard_cache.json"

            
      # 执行打卡
      - name: "Run AutoCard"
        env: 
          AUTOCARD_USER: ${{ secrets.AUTOCARD_USER }}
          AUTOCARD_PWD: ${{ secrets.AUTOCARD_PWD }}
          AUTOCARD_DINGTALK_URL: ${{ secrets.AUTOCARD_DINGTALK_URL }}
          AUTOCARD_DINGTALK_SECRET: ${{ secrets.AUTOCARD_DINGTALK_SECRET }}
          AUTOCARD_MAX_TRIAL: ${{ secrets.AUTOCARD_MAX_TRIAL }}
        run:  "java  --add-opens java.base/java.lang=ALL-UNNAMED -jar autocard.jar --app.autoCard.immediate=true"
